### ISSUE TITLE
Unable to Install Version 0.2.0 using conda

### ISSUE THREAD

**Issue by rantingswede373** [churchill-lab/g2gtools#14]
So using the documentation here: http://churchill-lab.github.io/g2gtools/#installation

```
conda config --add channels r

conda config --add channels bioconda

conda create -n g2gtools_2 jupyter ipykernel

source activate g2gtools_2

```
All of the above works fine, however when I go to install g2gtools within the virtual environment I just created (g2gtools_2) it attempts to install 0.1.31 and downgrade python to 2.7.X:

```
(g2gtools_2) $ conda install -c kbchoi g2gtools
...
g2gtools:                           0.1.31-py27_0          kbchoi
...
ipython:                            6.5.0-py36_0                    --> 5.8.0-py27_0                   
python:                             3.6.6-hc167b69_0                --> 2.7.15-h138c1fe_0              
```

If I try to specify the version number as 0.2.0 it fails:

```
conda install -c kbchoi g2gtools=0.2.0
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - g2gtools=0.2.0
  - bx-python[version='>=0.8']
  - python-lzo

Current channels:

  - https://conda.anaconda.org/kbchoi/osx-64
  - https://conda.anaconda.org/kbchoi/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch
  - https://conda.anaconda.org/salilab/osx-64
  - https://conda.anaconda.org/salilab/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

```

This is in spite of the fact that I can see correct version number if I search:

```
(g2gtools_2) $ conda search g2gtools
Loading channels: done
# Name                  Version           Build  Channel             
g2gtools                 0.1.29          py27_0  kbchoi              
g2gtools                 0.1.31          py27_0  kbchoi              
g2gtools                  0.2.0          py36_0  kbchoi              

```

I've tried to install bx-python separately but this also results in a PackagesNotFoundError.
I'm on OSX, conda version 4.5.4

**Comment by kbchoi-jax** [comment]
It should work now. I note that we made some bugfixes since v0.2.0. Could you please try installation again?
```
$ conda search -c kbchoi g2gtools
Loading channels: done
# Name                  Version           Build  Channel
g2gtools                 0.1.29          py27_0  kbchoi
g2gtools                 0.1.31          py27_0  kbchoi
g2gtools                  0.2.0          py36_0  kbchoi
g2gtools                  0.2.7          py27_0  kbchoi
g2gtools                  0.2.7          py36_0  kbchoi
```

**Comment by rantingswede373** [comment]
Still getting the error message as above. If I leave the version number off then g2gtools 0.1.31 installs
```
(g2gtools_3) $ conda install -c kbchoi g2gtools=0.2.7
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - g2gtools=0.2.7
  - bx-python[version='>=0.8']
  - python-lzo
```

**Comment by kbchoi-jax** [comment]
In your home directory, you should have `.condarc` file. The content should look like this.

```
channels:
  - defaults
  - kbchoi
  - bioconda
  - conda-forge
  - r
```

Fix it using your favorite text editor and then redo the whole installation please.

**Comment by rantingswede373** [comment]
Apparently the sequence or the presence of "salilab" was important. I replace the below text with the text you provided and the installation works! Version 0.2.7 installed without a hitch and seems to work with test data. Thank you for all your help!

channels:
  - bioconda
  - r
  - kbchoi
  - salilab
  - defaults
